language: python
python:
    - 3.6
    - 3.7
notifications:
    email: false

before_install:
    - sudo apt-get update
    - sudo apt-get -y install python3-pip
    - sudo pip3 install --upgrade pip
    - sudo pip3 install flake8

script:
    - python3 -m flake8 . --ignore=E501