from sys import version as PYTHON_VERSION
import platform

PROTOCOL_VERSION = (1, 2, 19) #(major, minor, patch)
RELEASE_STRING = "MumPy 1.0a"
OS_STRING = RELEASE_STRING
OS_VERSION_STRING = "Python %s - %s %s" % (PYTHON_VERSION, platform.system(), platform.release())

PING_INTERVAL = 15  # seconds

MESSAGE_TYPE_VERSION = 0
MESSAGE_TYPE_UDPTUNNEL = 1
MESSAGE_TYPE_AUTHENTICATE = 2
MESSAGE_TYPE_PING = 3
MESSAGE_TYPE_REJECT = 4
MESSAGE_TYPE_SERVERSYNC = 5
MESSAGE_TYPE_CHANNELREMOVE = 6
MESSAGE_TYPE_CHANNELSTATE = 7
MESSAGE_TYPE_USERREMOVE = 8
MESSAGE_TYPE_USERSTATE = 9
MESSAGE_TYPE_BANLIST = 10
MESSAGE_TYPE_TEXTMESSAGE = 11
MESSAGE_TYPE_PERMISSIONDENIED = 12
MESSAGE_TYPE_ACL = 13
MESSAGE_TYPE_QUERYUSERS = 14
MESSAGE_TYPE_CRYPTSETUP = 15
MESSAGE_TYPE_CONTEXTACTIONMODIFY = 16
MESSAGE_TYPE_CONTEXTACTION = 17
MESSAGE_TYPE_USERLIST = 18
MESSAGE_TYPE_VOICETARGET = 19
MESSAGE_TYPE_PERMISSIONQUERY = 20
MESSAGE_TYPE_CODECVERSION = 21
MESSAGE_TYPE_USERSTATS = 22
MESSAGE_TYPE_REQUESTBLOB = 23
MESSAGE_TYPE_SERVERCONFIG = 24
MESSAGE_TYPE_SUGGESTCONFIG = 25

AUDIO_TYPE_CELT_ALPHA = 0
AUDIO_TYPE_PING = 1
AUDIO_TYPE_SPEEX = 2
AUDIO_TYPE_CELT_BETA = 3
AUDIO_TYPE_OPUS = 4

